docs/design/Projeto de Web Service - RNF-IntgrCercom.md

Favor avaliar a aderência do commit ao plano de GCO do grupo 2.

Criando a definição do WS prevista em RNF-IntgrCercom

---

db/ddl/RD-CursSup-RD-AtuProfisEgres.sql

Adiciona scripts de integração de VISÃO DA ATUAÇÃO PROFISSIONAL DO
EGRESSO com a VISÃO DA DEFINIÇÃO DE CURSOS SUPERIORES

Adiciona scripts de integração ddl

---

db/ddl/RD-GestUsu.sql

Adiciona script ddl RD-GestUsu.

Adiciona script ddl RD-GestUsu

---

.travis.yml
pom.xml

Verificando se não há erros de dependências no projeto.

Adicionado maven lint.

---

src/test/java/br/ufg/inf/DivulgaEventComunTest.java
src/test/java/br/ufg/inf/DivulgaEventEgresTest.java
src/test/java/br/ufg/inf/servico/InvalidDataTestModule.java
src/test/java/br/ufg/inf/servico/ReportTestModule.java
src/test/java/br/ufg/inf/servico/ValidDataTestModule.java

Comentando testes que não estão funcionando.

G3 corrige testes

---

src/test/java/br/ufg/inf/SalvaPlaniEgresTest.java
src/test/java/br/ufg/inf/bkp/ConfigurarBackupTest.java

Comentado código fonte dos casos de teste feitos pelo @dyegospeciais no commit e34fc12d62a32e37156b0f008b122b3c0f3e054e para fazer o JUnit passar os testes.

Corrige paliativamente testes falhando no G1

---

test/java/br/ufg/inf/PoliticaRecebimentoMensagemTest.java

Classe de acordo com os stubs Usuario e PoliticaRecebimentoMensagem

Alterada classe Teste

---

docs/wiki/Plano-de-Gerência-de-Configuração.md

Reelaborei o Plano de GCS de acordo com as políticas atualmente aplicadas no projeto Sempre UFG, em todas as áreas.
@Yuri-M-Dias e @leonardo-freitas-1995, quero que leiam esse novo plano e comentem o que tiver de errado para corrigirmos e mandar ASAP para o professor @julianolopes, junto com o código-fonte feito no `develop`.
**Obs.:** Temos que fazer várias modificações no `develop` antes de mandar para `homolog` para atender o Plano de GCS.

Lança nova edição do Plano de Gerência de Configuração

---

src/test/java/br/ufg/inf/servico/ExecConsTest.java

Corrigida anomalia do teste que comparava datas.

---

src/main/java/br/ufg/inf/interfaces/Planilha.java
src/main/java/br/ufg/inf/interfaces/SalvaPlaniEgresInterface.java
src/test/java/br/ufg/inf/modelo/SalvaPlaniEgresTest.java
src/test/java/br/ufg/inf/stubs/PlanilhaStub.java
src/test/java/br/ufg/inf/stubs/SalvaPlaniEgres.java

Adiciona novamente as classes do requisito RF-SalvaPlaniEgres que se
perderam no merge dos repositórios.

Adiciona classes perdidas

---

src/main/java/br/ufg/inf/backup/RestauraBD.java
src/main/java/br/ufg/inf/backup/StubRestauraBD.java
src/main/java/br/ufg/inf/utils/StubRestauraBDUtils.java
src/test/java/br/ufg/inf/backup/StubRestauraBDTest.java

Arquivos de teste para restauração de bakup

G3 Restaura Bakup

---

src/main/java/br/ufg/inf/rd_gestimport/ConexaoDb.java
src/main/java/br/ufg/inf/rd_gestimport/Main.java
src/main/java/br/ufg/inf/rd_gestimport/RdGestImport.java
src/main/java/br/ufg/inf/rd_gestimport/Teste.java
src/main/java/br/ufg/inf/rd_gestimport/TesteEgressosIncorretos.java
src/main/java/br/ufg/inf/rd_gestimport/TesteEgressosRecebidos.java
src/main/java/br/ufg/inf/rd_gestimport/TesteEgressosReplicados.java
src/main/java/br/ufg/inf/rd_gestimport/TesteFimPeriodo.java
src/main/java/br/ufg/inf/rd_gestimport/TesteImportadosComSucesso.java
src/main/java/br/ufg/inf/rd_gestimport/TesteInicioPeriodo.java
src/main/java/br/ufg/inf/rd_gestimport/TestePK.java
src/main/java/br/ufg/inf/rd_gestimport/TesteTimestamp.java
src/main/java/br/ufg/inf/rd_gestimport/TesteUsuario.java

@julianolopes, fiz este Pull Request para o @higorquintao, que adiciona a aplicação Java que implementa testes para RD-GestImport de forma standalone, CLI, um banco passado como entrada por linha de comando.

Implementa testes RD-GestImport

---

src/test/java/br/ufg/inf/modelo/UsuarioTeste.java

Esse pull request tem por objetivo corrigir os impactos da mudança do tipo de dado do CPF de usuário na classe UsuarioTeste.

Corrige impactos do CPF em UsuarioTeste

---

.travis.yml

Algum merge mal feito com o arquivo do Travis fez a build ficar parada e não funcionar mais. Esse PR resolve esse problema.

[G3] Corrige build travis

---

src/web/js/polit_receb_msg/polit_receb_msg.js
src/web/pages/polit_receb_msg/configurar-mensagens-do-sistema.jsp

Adiciona arquivos referentes a implementação do Stoyboard seguindo
modelo proposto.

Implementa Stoyboard RF-PolitRecebMsg

---

src/main/java/br/ufg/inf/sempreufg/excecoes/ErroExecutarSQLException.java
src/main/java/br/ufg/inf/sempreufg/excecoes/TempoExpiradoException.java
src/main/java/br/ufg/inf/sempreufg/excecoes/TipoDBInvalidoException.java
src/main/java/br/ufg/inf/sempreufg/servico/RestauraBD.java

Criando estrutura para restauração de banco de dados

---

src/main/java/br/ufg/inf/sempreufg/dao/AreaDeConhecimentoDAO.java
src/main/java/br/ufg/inf/sempreufg/interfaces/AreaDeConhecimentoDAOInterface.java
src/main/java/br/ufg/inf/sempreufg/modelo/AreaDeConhecimento.java
src/main/java/br/ufg/inf/sempreufg/modelo/CursoUFG.java

Erro introduzido no commit 0101b91cd4abd0a5eebd1a1a2acd7203d64f3094 (autor: @rafaelmereb) que atrapalha a execução do projeto no PR #90 (autor: @evertongyn)

Corrige problema de declaração de classe abstrata em AreaDeConhecimento

---

src/web/pages/aprov_divulg_event/aprov_divulg_event.jsp
src/web/pages/aprov_divulg_event/informacoes_event.jsp

Adiciona arquivos referentes ao Storyboard de RF-AprovDivulgEvent,
listagem das solicitações de eventos a serem aprovados ou reporvados e
outra tela contendo informações sobre o evento.

Implementa Stoyboard RF-AprovDivulgEvent

---

docs/wiki/anexos/Relatorio-Resultados-Procedimentos-Inte-Visao-AtruProfis-E-CursSup.md
docs/wiki/anexos/v&v/Documento-Procedimentos-Inte-Visao-AtruProfis-E-CursSup.md
src/main/java/br/ufg/inf/sempreufg/enums/FormaIngressoInstituicao.java
src/main/java/br/ufg/inf/sempreufg/enums/NaturezaOrganizacao.java
src/main/java/br/ufg/inf/sempreufg/modelo/Atuacao.java
src/main/java/br/ufg/inf/sempreufg/modelo/CursoOutrasIES.java
src/main/java/br/ufg/inf/sempreufg/modelo/Organizacao.java

Classes utilizadas para testes realizados e documentação gerada pelos testes de integração da Visão da Atuação Profissional do Egresso e Visão da Definição de Cursos Superiores.

G3 teste integracao visao atuacao e visao definicao

---

src/main/java/br/ufg/inf/sempreufg/dao/AvalSolicDivulgEventDAO.java
src/main/java/br/ufg/inf/sempreufg/interfaces/AvalSolicDivulgEventInterface.java
src/main/java/br/ufg/inf/sempreufg/modelo/AvalSolicDivulgEvent.java
src/main/java/br/ufg/inf/sempreufg/modelo/DivulgacaoNoticia.java

Adiciona arquivos necessários para a Avaliação de Solicitação de
Divulgação de Evento.
Foi necessário criar um arquivo mock para DivulgacaoNoticia.

Implementa RF-AvalSolicDivulgEvent
